"""add txtype field

Revision ID: 30ec90761d38
Revises: c2d7e343052b
Create Date: 2022-04-26 09:45:53.518221

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '30ec90761d38'
down_revision = 'c2d7e343052b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('txType', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'txType')
    # ### end Alembic commands ###
