"""init

Revision ID: 95079a96bc81
Revises: 
Create Date: 2022-04-08 12:01:37.380666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '95079a96bc81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('topics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('filterTree', sa.JSON(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filterType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repeats', sa.Integer(), nullable=False),
    sa.Column('messageTemplate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filter')
    # ### end Alembic commands ###
